Add doc
lightsources/BES-XPCS-Pilot pull request #41
Opened 2021-05-18 22:35 UTC by JulReinhardt

Add doc string explanation to all arguments. Some input needed, see TODO

2021-05-19 18:11 UTC, prjemian commented on creator/nx_creator_xpcs.py
> +        # TODO fix/extend documentation
Maybe could remove this TODO line and wait for issues to fix specific lines?

2021-05-19 18:13 UTC, prjemian commented on creator/nx_creator_xpcs.py
> +        :param : g2_unit unit for g2 is usually arbitrary units
` unit for g2 is usually "a.u." (arbitrary units)`

2021-05-19 18:14 UTC, prjemian commented on creator/nx_creator_xpcs.py
> +        :param : C2_unit unit for C2 is usually arbitrary units
as g2_unit above

2021-05-19 18:15 UTC, prjemian commented on creator/nx_creator_xpcs.py
> +        :param : tau_unit any unit of time
`any time units`

2021-05-19 18:22 UTC, prjemian requested changes
Some wording to be changed as noted.  Also, consistency in use of `unit` *v.* `units`. In many cases, the text might be a single value, such `nm` or `erg` (clearly singular).  In other cases, the units could involve some mathematic representation, such as `dyne*cm` or `s^-1 * m^-2 sr^-1` (clearly plural).

NeXus chose the plural use `units` which is consistent with conversational use they observed.

2021-05-20 05:36 UTC, JulReinhardt commented
Thanks @prjemian please have a look a the changes.

2021-07-29 02:27 UTC, prjemian commented on loader/nx_loader_aps.py
> +            i_units='a.u.'
Why not `I_units`?  (upper case to match `I` field)

2021-07-29 02:31 UTC, prjemian commented on creator/nx_creator_xpcs.py
> +                logger.warning("WARNING: '%s': Supplied units (%s) does not match expected units (%s)",
`does` -> `do`

2021-07-29 02:31 UTC, prjemian commented on creator/nx_creator_xpcs.py
> +            logger.info("Info: arbitrary units supplied for '%s' in form of '%s' np units conversion applicable",
`np` -> `no`

2021-07-29 02:32 UTC, prjemian requested changes
changes as noted

2021-08-13 16:34 UTC, ambarb commented
@JulReinhardt is this still needed for NXxpcs V1?

2021-08-13 16:34 UTC, prjemian commented
@JulReinhardt : Looks like it's time for me to review again, right?

2021-09-10 16:58 UTC, ambarb commented
This is for both the creator and NXdefinition.  Ready for review.

We merge after review if no glaring issues.  Wait for XPCS community comments before addressing.

2021-09-12 16:47 UTC, prjemian approved these changes

2021-09-12 16:48 UTC, merged